QDEV-687 Public API for searching with Qase Query Language
qase-tms/specs pull request #10
Opened 2021-06-29 16:02 UTC by abelharisov

2021-06-29 20:45 UTC, kamilsk requested changes
please rollback code generation part.

motivation: we have to focus on the most valuable part of the pull request - specification changes. you can generate examples a little bit later, then your pr will be approved, for example.

2021-06-29 21:28 UTC, abelharisov commented
> please rollback code generation part.
> 
> motivation: we have to focus on the most valuable part of the pull request - specification changes. you can generate examples a little bit later, then your pr will be approved, for example.

done

2021-06-30 17:01 UTC, kamilsk reviewed
LGTM

minor changes are needed, but we can discuss them outside the pr

2021-06-30 17:01 UTC, kamilsk commented on src.yaml
>      Offset: { $ref: './parameters/pagination/Offset.yaml' }
what do you think if we rename them to PageLimit, PageOffset?

2021-06-30 17:01 UTC, kamilsk approved these changes

2021-06-30 17:02 UTC, kamilsk commented
please do not include generate part, we do it later. maybe we extract it from the specs

2021-07-01 06:24 UTC, merged