Single result endpoint
qase-tms/specs pull request #137
Opened 2024-01-24 23:21 UTC by dissipative

Several changes have been made:

- Added a new endpoint.
- Removed `/v1` from base URL and added it to each path since readme.com doesn't support server overriding (it is necessary for `/v2` paths). Source: https://docs.readme.com/main/docs/openapi-compatibility-chart#path-item-object
- Added a missing `testops-api/README.md` (initially generated with ChatGPT; suggestions for changes are welcome).
- Removed full stops at the end of summaries. English language conventions suggest omitting them in headings, and these are used as H1 elements after page rendering.

2024-01-25 19:40 UTC, nipisarev approved these changes

2024-01-25 20:26 UTC, abelharisov approved these changes

2024-01-25 23:17 UTC, n3r requested changes
I don't think that it is a good idea to keep all versions of API endpoints in the same spec file. We get a mess of different endpoints. Customers should work with a particular version of the package. I agree with statements described here: https://stackoverflow.com/questions/54691517/service-versioning-in-openapi

2024-01-26 14:49 UTC, dissipative commented
> I don't think that it is a good idea to keep all versions of API endpoints in the same spec file. We get a mess of different endpoints. Customers should work with a particular version of the package. I agree with statements described here: https://stackoverflow.com/questions/54691517/service-versioning-in-openapi

This is a good point about avoiding a single file overwhelmed with paths and versions. Consequently, I revised src.yaml into src_v1.yaml and src_v2.yaml. Changes to the workflow required some manual actions on the readme.com account, so you can immediately see the results of my changes at https://developers.qase.io/.

I have just one concern about segregating the API versions: the second version can't replace the first right now in any way — it consists of just one endpoint, and one needs to use a special client to utilise it.

2024-01-29 08:10 UTC, dissipative commented
UPD: now there are two paths for specs: 
- `testops-api/v1` 
- `testops-api/v2`

2024-01-29 11:55 UTC, merged