fix typo
qase-tms/specs pull request #67
Opened 2021-12-15 12:06 UTC by sklmx

2021-12-15 14:29 UTC, kamilsk requested changes

2021-12-15 14:29 UTC, kamilsk commented on schemas/Result.create.yaml
> +    description: Could be used instead of case_id
could you also add a dot please?

2021-12-15 14:29 UTC, kamilsk commented on schemas/Result.create.yaml
> +    description: Could be used instead of case_id
and please wrap case_id:

```
`case_id`
```

2021-12-15 20:15 UTC, sklmx commented on schemas/Result.create.yaml
> +    description: Could be used instead of case_id
done

2021-12-16 07:02 UTC, kamilsk approved these changes

2021-12-16 07:02 UTC, merged